### PR TITLE
Allow admin to change any password

### PR DESCRIPTION
**Pull request by djangoliv**
Add endpoint to allow admin to change the password for any users.

https://github.com/jupyterhub/nativeauthenticator/issues/90

### CODE REVIEW

**Comment by djangoliv** [comment]
@lambdaTotoro 
Thank you, I changed the message. I also added a user existence check.

**Comment by lambdaTotoro** [comment]
Also, since JupyterHub (currently) requires a python version of [>=3.5](https://github.com/jupyterhub/jupyterhub/blob/master/setup.py#L22), but f-Strings were introduced in Python [3.6](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498), please rewrite to not use f-Strings.

**Comment by djangoliv** [comment]
@lambdaTotoro Right, done.

**Comment by lambdaTotoro** [comment]
Sorry it took a while, but this PR looks good to me. Tests are also green. I'll merge.

**Pull request merged**
