### PR TITLE
fix orm for support mysql

### PR DESCRIPTION
**Pull request by 00Kai0**
Hi @leportella 
The issue is `sqlalchemy.exc.CompileError: (in table 'users_info', column 'username'): VARCHAR requires a length on dialect mysql`.
We must declare length for `String` or `Unicode` in mysql.

### CODE REVIEW

**Comment by leportella** [comment]
@00Kai0 sorry for taking so long! Do you mind rebasing this please?

**Comment by 00Kai0** [comment]
@leportella Sorry to reply to you so late. I have rebase it.

**Comment by chicocvenancio** [comment]
Just ran into this error today. Thanks for the fix @00Kai0

**Comment by mttcnnff** [comment]
@leportella can you guys merge this and create a release please? I'm currently blocked by it and would love to use this change

**Pull request merged**
